<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>slide generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="slide, WOW Slider, Slideshow CSS3, Slideshow Photo" />
	<meta name="description" content="slide created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/arts_deppt..jpg" alt="arts_deppt." title="arts_deppt." id="wows1_0"/></li>
<li><img src="data1/images/class_room.jpg" alt="class_room" title="class_room" id="wows1_1"/></li>
<li><img src="data1/images/gaya_college.jpg" alt="gaya_college" title="gaya_college" id="wows1_2"/></li>
<li><img src="data1/images/hostel.jpg" alt="hostel" title="hostel" id="wows1_3"/></li>
<li><img src="data1/images/oditorium.jpg" alt="oditorium" title="oditorium" id="wows1_4"/></li>
<li><img src="data1/images/principal_house.jpg" alt="principal_house" title="principal_house" id="wows1_5"/></li>
<li><img src="data1/images/teaching_teacher.jpg" alt="teaching_teacher" title="teaching_teacher" id="wows1_6"/></li>
</ul></div>


	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>